ray:
  num_cpus: 96
  num_gpus: 4

dataset:
  input_manifest: dataset/T2V-5k-filter.jsonl

always_stages:
  - input_partition
  - video_reader
  - clip_writer

operators:
  video_split_by_scene_mapper:
    - video_scene_split
    - clip_transcoding
  video_aesthetics_filter:
    - uniform_3_frame_sampling
    - video_aesthetics_filter
  video_optical_flow_filter:
    - uniform_3_frame_sampling
    - video_optical_flow_filter
  video_captioning_camera_motion_mapper:
    - uniform_16_frame_sampling
    - video_captioning_camera_motion

stage_order:
  - input_partition
  - video_reader
  - video_scene_split
  - clip_transcoding
  - uniform_3_frame_sampling
  - video_aesthetics_filter
  - video_optical_flow_filter
  - uniform_16_frame_sampling
  - video_captioning_camera_motion
  - clip_writer

stages:
  input_partition:
    cpus: 1
    gpus: 0
    batch_size: 1
    num_workers: 1
  video_reader:
    cpus: 1
    gpus: 0
    batch_size: 1
    num_workers: 3
  video_scene_split:
    cpus: 1
    gpus: 0
    batch_size: 1
    num_workers: 6
    params:
      detector: ContentDetector
      threshold: 27.0
      min_scene_len: 10
      show_progress: false
      max_scene_num: 3
      meta_time_out: 60
  clip_transcoding:
    cpus: 1
    gpus: 0
    batch_size: 1
    num_workers: 12
    params:
      num_cpus_per_worker: 1.0
      encoder: libx264
      encoder_threads: 1
      encode_batch_size: 3
  uniform_3_frame_sampling:
    cpus: 1
    gpus: 0
    batch_size: 1
    num_workers: 15
    params:
      sampling_method: uniform
      frame_count: 3
  video_aesthetics_filter:
    cpus: 1
    gpus: 0.05
    batch_size: 8
    num_workers: 4
    params:
      hf_scorer_model: /team/xyq/data_juicer/models/shunk031/aesthetics-predictor-v2-sac-logos-ava1-l14-linearMSE
      min_score: 0.4
      max_score: 1.0
      frame_sampling_method: uniform
      frame_num: 3
      reduce_mode: avg
      any_or_all: any
  video_optical_flow_filter:
    cpus: 2
    gpus: 0.30
    batch_size: 16
    num_workers: 11
    params:
      optflow_model_path: /team/xyq/data_juicer/models/Unimatch/gmflow-scale2-regrefine6-mixdata-train320x576-4e7b215d.pth
      min_score: 0.15
      max_score: 20.0
      frame_sampling_method: uniform
      frame_num: 3
      reduce_mode: avg
      any_or_all: any
      stride: 2
      scale_by_fps: true
  uniform_16_frame_sampling:
    cpus: 1
    gpus: 0
    batch_size: 1
    num_workers: 4
    params:
      sampling_method: uniform
      frame_count: 16
  video_captioning_camera_motion:
    cpus: 1
    gpus: 0.05
    batch_size: 6
    num_workers: 4
    params:
      hf_model_path: /team/xyq/data_juicer/models/MCG-NJU/videomae-large
      num_frames: 16
      max_duration: 8
      torch_dtype: bfloat16
  clip_writer:
    cpus: 1
    gpus: 0
    batch_size: 4
    num_workers: 2
    params:
      generate_embeddings: false
      generate_previews: false
      generate_captions: true
      caption_models: []
      enhanced_caption_models: []

experiments:
  4op:
    operators:
      - video_split_by_scene_mapper
      - video_aesthetics_filter
      - video_optical_flow_filter
      - video_captioning_camera_motion_mapper
